name: debug_logger
description: Logging utility used for debugging
version: 0.0.21
author: abdi.adan@healthcloud.co.ke
homepage: https://github.com/savannahghi/debug_logger

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.0

flutter:
