name: debug_logger
description: A liteweight utility used for logging values to debug console.
version: 0.0.24
homepage: https://github.com/savannahghi/debug_logger
repository: https://github.com/savannahghi/debug_logger
issue_tracker: https://github.com/savannahghi/debug_logger/issues
documentation: https://github.com/savannahghi/debug_logger/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.0

flutter:
