name: sil_logger
description: Logging utility used for debugging
version: 0.0.21
author: dmwangi@savannahinformatics.com
homepage: https://github.com/savannahghi/sil_logger

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.0

flutter:
