version: 2.1
executors:
  docker-machine:
    docker:
      - image: "circleci/android:api-29"

commands:
  installpackages:
    description: "Install flutter to latest version and install dependencies"
    steps:
      - checkout
      - run:
          name: Install flutter
          command: bash install_flutter_ci.sh
      - save_cache:
          key: flutter-root-and-deps-linux-v5
          paths:
            - $CIRCLE_WORKING_DIRECTORY/.dart_tool/
            - $CIRCLE_WORKING_DIRECTORY/.flutter-plugins
            - $CIRCLE_WORKING_DIRECTORY/.flutter-plugins-dependencies
            - $CIRCLE_WORKING_DIRECTORY/.packages
            - $CIRCLE_WORKING_DIRECTORY/.pub-cache/
            - $CIRCLE_WORKING_DIRECTORY/.pub/

jobs:
  run-tests-and-coverage:
    executor: docker-machine
    steps:
      - installpackages
      - run:
          name: "Setup flutter environment variable"
          command: |
            echo 'export PATH=/home/circleci/flutter/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - flutter-root-and-deps-linux-v5
      - run:
          name: Analyze, test and report coverage
          no_output_timeout: 5m
          command: |
            flutter clean        
            flutter analyze
            sudo apt-get -qq update
            sudo apt-get install -qqy lcov python3-pip 
            pip3 install -Uqqq lxml && pip3 install -Uqqq beautifulsoup4
            flutter test --coverage test
            genhtml -q -o coverage coverage/lcov.info
            python3 check_coverage.py
